---

- name: génération csr and key for CA
  command: "openssl req -new -nodes -newkey rsa:2048 -subj \"/C=FR/ST=France/L=Paris/O=IT/CN={{ hostname_registry }}\" -days 3650 -keyout {{ pathCAkey }} -out {{ pathCAcsr }} -config {{ pathCAconf }} -extensions v3_ca"
  args: 
    creates: "{{ pathcrt }}"

- file: path=CA/newcerts state=directory owner="root" group="root" mode="0755"

- name: génération certificat CA
  command: "openssl ca -batch -config {{ pathCAconf }} -policy policy_anything -out {{ pathcrt }} -infiles {{ pathCAcsr }}"
  args: 
    creates: "{{ pathcrt }}"

- name: copie clef CA
  copy: >
    src="{{ pathCAkey }}" dest="{{ pathkey }}" remote_src=true
